services:
  # 1. The Redis Database
  - type: redis
    name: redis
    plan: free
    # --- ADD THIS SECTION ---
    ipAllowList:
      - ip: 0.0.0.0/0
        description: "Allow all internal traffic"
    # ----------------------

  # 2. The Web Server
  - type: web
    name: web
    env: node
    plan: free
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  # 3. The Background Worker
  - type: worker
    name: worker
    env: node
    plan: free
    startCommand: "node worker.js"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString